language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
services:
 - postgresql
before_script:
  - psql -c "CREATE DATABASE shoppinglist;" -U postgres
  - psql -c "CREATE USER shoppinglist WITH PASSWORD 'bar';" -U postgres
  - alembic upgrade head
script:
  - python3.6 tests.py
  - coveralls

after_success:
  - nosetests --with-coverage
  - coveralls